### ISSUE TITLE
uint64 and int64 decoding

### ISSUE THREAD

**Issue by YaroShkvorets** [pinax-network/antelope-abi2rs#8]
`uint64`/`int64` fields in ABI are typed as `u64`/`i64` by abi2rs.

However, in Firehose, eos-go would encode them in JSON as a number if the value is < ffffffff and string otherwise.

This is done for compatibility with Javascript that uses floating-point representation for numbers and can't hold numbers that are >= 2^52.

Need to handle that somehow, otherwise serde throws an error on big values.

See [this discussion on serde](https://github.com/serde-rs/json/issues/329) and the [serde_with crate](https://docs.rs/serde_with/latest/serde_with/)

**Comment by Krow10** [comment]
Just to add a few more links that can be helpful to resolve this:
- https://github.com/serde-rs/json/issues/412 -> The solution has been implemented as an external library `serde-aux` available [here](https://github.com/vityafx/serde-aux).
- https://stackoverflow.com/a/37871403 -> Uses the `Visitor` pattern also to deserialize either u64 or string

**Comment by YaroShkvorets** [comment]
Implemented custom deserializer for uint64 and int64 types
